---
- hosts: ul-servers
  tasks: 
     
     - name: Deploying mobile linux {{ Release_Tag }} on UL Servers
       ignore_errors: True
       shell: |
         curl https://mobile-automation-testing.s3.amazonaws.com/mobile-automation/{{ Repo_Owner }}/{{ Release_Tag }}/mobile_linux -o /Users/ltadmin/Documents/mobile_linux
       
