---
- hosts: ul-servers
  tasks: 
     
     - name: Deploying mobile linux {{ Release_Tag }} on UL Servers
       ignore_errors: True
       shell: |
         #pwd
         #ls
         echo "Jenkins Run" >> jenkins.txt
         echo "$(date)" >> jenkins.txt
         #curl https://github.com/LambdaTest/mobile-automation/releases/download/{{ Release_Tag }}/mobile_linux -o /home/ltadmin/Picture/mobile_linux
         #curl https://mobile-automation-testing.s3.amazonaws.com/mobile-automation/{{ Repo_Owner }}/{{ Release_Tag }}/mobile_linux -o /home/ltadmin/Downloads/mobile_linux
       
